levitsky/pyteomics

.gitignore, pyteomics/mzml.py
This fixes #5.
This may be a breaking change for cases where `non-standard data array` *is* specified, but a userParam naming the array is present but does not end with `"array"`. Previously, the name of the array would be `"non-standard data array"`, but now it would be whatever the longest userParam is.
=> Add more aggressive name guessing for malformed but maybe recoverable non-standard data arrays

pyteomics/pepxml.py
* Fixes xpath bugs in pepxml.roc_curve() that caused a fatal error [XPathEvalError: Invalid predicate]
* Adds "charge" and "tag" keys to the output to make the function usable in real world.
=> Fix xpath, improve pepxml.roc_curve()

AUTHORS, CHANGELOG, pyteomics/mztab.py, tests/test_mztab.py, tests/test_mztab2.mztab
Class MzTab was extended to parse sections from mztab 2.0.  The following sections were added: "small molecule feature table" and "small molecule evidence table".
=> Parsing mztab 2.0 sections in `MzTab`

pyteomics/mztab.py
Accepts version numbers that do not necessarily contain 3 numbers (x.x.x) - can read versions that contain 1 or 2 numbers (x) or (x.x)
=> Fixed version parsing

pyteomics/mass/unimod.py
Addresses #31 
With the migration underway at SQLAlchemy from 1.3 to 1.4, internal details that I shouldn't have relied on are changing as they prepare for a major version change. This now explicitly gathers model types without relying on SQLAlchemy doing it for us indirectly.
=> Fix Unimod Compatibility With SQLAlchemy 1.4.X 

pyteomics/mzid.py, pyteomics/xml.py
Closes #33 
The root cause in #33 is that when processing a `FragmentationArray`, the `measure_ref` attribute must be resolved. This leads to a `get_by_id` call, but the requested ID is not in the index, so it leads to a sequential scan along the entire file. Each `SpectrumIdentificationItem` contains at least three `FragmentationArray`, each of which references all three `Measure` elements, leading to the seeming stand-still for a single `SpectrumIdentificationResult`
To avoid this cropping up in the future, I've added all reference-able element types to the offset index. We'll see if this leads to an undesirable slowdown in initialization speed as it makes the indexer generate a more complex tokenizer pattern.
=> Index additional tags for mzIdentML

pyteomics/mzmlb.py
Sure enough, the feature was merged and then I started doing more serious performance testing. It appears that `h5py` does not attempt to do serious caching of decompressed chunks in memory for simplicity, so each attempt to read a slice of the dataset requires decompressing a whole chunk of data and then taking the requested slice on demand every time, making sequential reading of the mzMLb file orders of magnitude slower than reading the equivalent compressed mzML.
This feature adds an extra intermediate caching layer to the `MzMLb` object which caches a chunk of each array in memory under the assumption that the next read will be in the same region. This boosts the performance to being twice as fast as the equivalent mzML file.
=> Improve mzMLb read performance with array cache

.github/workflows/pythonpackage.yml, pyteomics/mzml.py, test-requirements.txt
Right now, we can detect a mzML binary data array non-standard data array's name if it is a userParam with the word "array" in its name.
```xml
<binaryDataArray encodedLength="20">
<cvParam cvRef="PSI-MS" accession="MS:1000786" name="non-standard data array"/>
<userParam name="frobnication wavelength array"/>
<cvParam cvRef="PSI-MS" accession="MS:1000574" name="zlib compression" value=""/>
<cvParam cvRef="PSI-MS" accession="MS:1000521" name="32-bit float" value=""/>
<binary>eJxjYGiwZxhBGADvOCzF</binary>
</binaryDataArray>
```
It might also be the value of the "non-standard data array" cvParam according to the spec and CV:
```xml
<binaryDataArray encodedLength="20">
<cvParam cvRef="PSI-MS" accession="MS:1000786" name="non-standard data array" value="frobnication wavelength array"/> …
```
=> Properly detect non-standard array name when it is a term value

pyteomics/proforma.py, setup.py, test-requirements.txt, tests/test_proforma.py
@bittremieux highlighted a few cases that were vague in the specification, and it turns out my parser didn't handle them correctly.
Also, recent changes to `psims` cause it to do more aggressive type coercion of CV terms, removing the need to do it in the `proforma` module itself. I've updated the minimum version required for the `proforma` feature to reflect this.
While there, I added a bit more documentation.
=> Fix ProForma Parsing and Update Docs

pyteomics/usi.py
I noticed a service started to respond with integer and float values for attributes, which broke the attribute type coercion code. This fixes the issue, making the code work on both cases.
=> Handle cases where the PROXI server responds with properly typed numerical values for attributes

pyteomics/fasta.py, tests/test_fasta.py
Shuffle function in fasta module is updated to include two new argument
`keep_M` preserve **only** N-terminal methionine
`fix_aa` allows excluding some of amino acids from shuffling (i.e. position is preserved)
=> Shuffling that preserves some amino acids

doc/source/api/auxiliary.rst, doc/source/data.rst, doc/source/data/controlled_vocabulary_terms.rst.inc, doc/source/data/unit_handling.rst.inc, pyteomics/auxiliary/structures.py, pyteomics/mzid.py, pyteomics/mzml.py, pyteomics/mzmlb.py, pyteomics/traml.py
As shown by #56, the components for handling units were not documented. This PR adds explicit documentation for these to the mzML(b), mzIdentML, and TraML pages. This also adds more text describing the `cvstr` and `cvquery` mechanisms.
=> Document the unit handling and controlled vocabulary string features

doc/source/data/unit_handling.rst.inc
The unit string should have been "second", otherwise it isn't consistent with the other code in the example, or with how the UO term is named.
=> DOCFIX Remove trailing "s" from example code

pyteomics/auxiliary/utils.py, pyteomics/pylab_aux.py
@bittremieux I'm thinking of adding integration with [spectrum_utils](https://github.com/bittremieux/spectrum_utils) to `pylab_aux.annotate_spectrum`. What do you think?
The idea is to take the work of transforming the spectra from `pyteomics` format to `spectrum_utils` off the user. It can be tested with the following (based on [spectrum_utils doc](https://spectrum-utils.readthedocs.io/en/latest/quickstart.html)):
```python
from pyteomics import pylab_aux as pa, usi
spectrum = usi.proxi('mzspec:PXD004732:01650b_BC2-TUM_first_pool_53_01_01-3xHCD-1h-R2:scan:41840', 'massive')
peptide = 'WNQLQAFWGTGK'
pa.annotate_spectrum(spectrum, peptide, precursor_charge=2, backend='spectrum_utils',
scaling='root', min_intensity=0.05, ion_types='aby', remove_precursor_peak=True, colors={'a': 'yellow'}) …
```
=> Addition of spectrum_utils backend

tests/test_usi.py
This patch fixes the USI testing backend, it seems like the Peptide Atlas USI service is down, while the MassIVE service is still working. For all example USIs at http://proteomecentral.proteomexchange.org/usi/, MassIVE works while PeptideAtlas does not.
=> Switch USI test backend

doc/source/api/proforma.rst, doc/source/api/unimod.rst, pyteomics/mass/mass.py, pyteomics/mass/unimod.py, pyteomics/proforma.py, tests/test_proforma.py
This PR implements some of the changes discussed in #82 but does not outright bundle the CV source file with the codebase. It adds documentation about how the CV can be loaded from disk instead of the internet.
It also re-structures the `pyteomics.proforma` documentation a bit and in need of a bit meditation I wrote a `fragments` method for the `Proforma` type.
=> Improve documentation of Unimod loading and highlight in ProForma

pyteomics/fasta.py, tests/test_fasta.py
[The Uniprot documentation](https://www.uniprot.org/help/fasta-headers) specifies which key-value pairs can appear in the FASTA headers and in what order:
```
>db|UniqueIdentifier|EntryName ProteinName OS=OrganismName OX=OrganismIdentifier [GN=GeneName ]PE=ProteinExistence SV=SequenceVersion
```
Up to now, the parser tried to match them loosely, relying on the assumption that `=` only occurs as a key-value delimiter in FASTA headers. That is not true, hence it is non-trivial to discern parts of the protein name from arbitrary keys and values. Example of breaking entry:
```
>tr|Q9S8M8|Q9S8M8_WHEAT FRIII-2-VIII=GAMMA-gliadin (Fragment) OS=Triticum aestivum OX=4565 PE=1 SV=1
```
This PR changes the pattern so that only the documented keys are parsed in the order that they are listed in the …
=> Hard-code key=value pairs in Uniprot headers as described in the spec

pyteomics/mzml.py, pyteomics/mzxml.py
Fixes #104
Similar problem found for `mzxml` which is fixed as well. `mzmlb` does not this option in its `read` function.
=> Pass through the decode_binary parameter in read for mzml and mzxml

doc/source/_static/example_msms.py
https://github.com/levitsky/pyteomics/blob/5661fd40512884113adf6699388cbf69d4a93c02/doc/source/_static/example_msms.py#L34
If I am not mistaken this loop should go from inclusive 1 to inclusive len(peptide) - 1 to generate all fragment masses. Since the upper bound of range is exclusive we don't need to substract the 1 here.
The previous code would miss one ion of each ion type.
E.g.
For b ions PEPT would give P, PE and missing PEP since "PEPT"[:2] = "PE" where 2 is the maximum of iterable i
Similarly for y ions it would give EPT, PT and missing T since "PEPT"[2:] = "PT"
=> Fix iteration in example for calculating theoretical fragment m/z

pyteomics/fasta.py, tests/test_fasta.py
This PR adds an entry to FASTA file parsers that contains raw (i.e. non-parsed header). The latter is used by the `write` to write parsed protein entries.
Useful, for the fast filtering of FASTA files, for example:
```
from pyteomics import fasta
fasta_entries = fasta.UniProt('uniprot_multi_organism.fasta')
fasta.write([protein for protein in fasta_entries if protein.description.get('OX', -1) == 123], 'uniprot_single_organism.fasta')
```
=> Add raw fasta file header to parsers

pyteomics/fasta.py
This continues the discussion from #120 and uses the new metaclass to replace the `_add_init` decorator.
Potential weak links:
=> Use metaclass to add __init__ to flavored fasta parsers

pyteomics/proforma.py
Fixes #128 
If available, `proforma` will use `psims`'s Unimod API instead. This way applications and users can use `psims`'s caching features and have access to a fallback copy of the supported controlled vocabularies when the internet is inaccessible.
=> If psims is available, use its Unimod because it caches and vendors

pyteomics/proforma.py, tests/test_mgf.py
Fixes #132 
The `psims` implementation used one big dispatching resolver for all identifiers, and I forgot to include a `by_id` alias. `__getitem__` should work as intended both with and without `psims`. If this is a Py2 issue, it may be harder to patch.
=> Fix UniMod by ID

pyteomics/mass/mass.py, pyteomics/proforma.py, tests/test_mass.py
This PR adds a new optional argument to `mass.calculate_mass`, `proforma`. If specified, it should be a ProForma string or a `proforma.ProForma` object. Its `mass` property is then converted to m/z if needed.
=> Calculate m/z for proforma in calculate_mass

pyteomics/mass/unimod.py
In sqlalchemy version 2.0, `declarative_base` and `DeclarativeMeta` moved to another module. This adds a try-except around the imports to retain compatibility with sqlalchemy <2.0 and >2.0. Before, the import still worked, but resulted in `MovedIn20Warning` (for example: https://github.com/compomics/psm_utils/actions/runs/6239222484/job/16936699966?pr=50#step:7:35)
=> Update imports for sqlalchemy v2.0 changes

pyteomics/proforma.py
All ModificationResolver types now use an in-memory cache for resolved modification definitions, reducing overhead of resolving the same rule over and over again.
Sub-classes should move their implementation of `resolve` to the `_resolve_impl` method, otherwise the cache will not be used.
To disable the cache for a resolver instance, call `resolver.enable_caching(False)`.
This implements support for the syntax discussed in https://github.com/HUPO-PSI/ProForma/issues/6 to include constant modification rules that apply to specific sequence terminals with or without specific amino acids.
=> Add modification caching; Constant terminal mods for ProForma

pyteomics/usi.py
The current URL is a development URL that no longer works.
=> Fix PRIDE PROXI server URL

pyteomics/proforma.py, tests/test_proforma.py
Closes #157 
This issue also masked an error in one of the unit tests, where an attribute was misspelled. Previously, I was silently ignoring errors because not all tags have a mass value. Instead, now each tag is asked if it is expected to have a mass value, and if so, it is accessed and added to the accumulator.
Since modifications load lazily, and then read the mass value out of a `dict`, the `KeyError` could either be the result of a lookup failure for a modification resolver, or a lookup failure for the resolved properties of the modification, which would silence both mass lookup issues and modification resolution issues. Both of these are now resolved.
=> Fix silencing of errors during ProForma mass calculations

.github/workflows/pythonpackage.yml, CHANGELOG, pyteomics/auxiliary/__init__.py, pyteomics/auxiliary/utils.py, pyteomics/mass/mass.py, tests/test_auxiliary.py, tests/test_util.py
Closes #162.
This checks  that the path passed to `mass.Unimod` has a URL prefix, and adds `file:` if no prefix is specified. It also converts a local path to an absolute one and adds support for `Path` arguments.
=> Ensure URL prefix when creating a mass.Unimod

doc/source/data/indexing.rst.inc, pyteomics/auxiliary/__init__.py, pyteomics/auxiliary/file_helpers.py, tests/test_util.py
Currently, the tests invoking `map()` method of readers produce `DeprecationWarning` on Linux:
```
/usr/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=59787) is multi-threaded, use of fork() may lead to deadlocks in the child.
self.pid = os.fork()
```
That is because the implementation of `TaskMappingMixin` spawns both threads and processes, and the default method of spawning processes on Linux is currently `fork`, which is considered generally unsafe in a multi-threaded context. Currently `os.fork()` raises a warning when it detects multiple threads, and in Python 3.14 the default for Linux will apparently change to `spawn`, as it already is on Windows and macOS.
Discussion on the matter: https://discuss.python.org/t/concerns-regarding-deprecation-o …
=> Make start method for map() configurable, avoid fork by default
